export type MenuItem = {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
  image_url: string;
  is_vegetarian: boolean;
  is_gluten_free: boolean;
  is_spicy: boolean;
  preparation_time_minutes: number;
  is_available: boolean;
  current_stock: number;
  low_stock_threshold: number;
};

export type CartLine = {
  key: string;
  menuItemId: number;
  title: string;
  unitPrice: number;
  quantity: number;
  spiceLevel: string;
  note: string;
  imageUrl: string;
};

export const CATEGORIES = [
  "All",
  "Soups",
  "Noodles",
  "Rice",
  "Curries",
  "Salads & Thoke",
  "Snacks",
  "Sides",
  "Desserts",
  "Drinks",
  "Specials",
] as const;

/** Categories staff can assign in menu admin (no "All"). */
export const MENU_CATEGORY_OPTIONS = CATEGORIES.filter((c) => c !== "All");

/** Working HTTPS photos (Unsplash). Replace with Cloudinary public_ids after upload. */
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=640&q=70`;

/** Local authentic dish photos in /public/menu (Myanmar + a few corrected items). */
const menuImg = (slug: string) => `/menu/${slug}.jpg`;

export const DEMO_MENU: MenuItem[] = [
  {
    id: 1,
    title: "Truffle Wagyu Burger",
    description: "Aged A5 Wagyu, black truffle aioli, Gruyère, brioche",
    category: "Mains",
    price: 14000,
    image_url: img("photo-1568901346375-23c9450c58cd"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 15,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 2,
    title: "Artisanal Cappuccino",
    description: "Ethiopia Guji espresso, oat milk, cocoa dusting",
    category: "Coffee & Drinks",
    price: 3500,
    image_url: img("photo-1572442388796-11668a67e53d"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 4,
    is_available: true,
    current_stock: 50,
    low_stock_threshold: 10,
  },
  {
    id: 3,
    title: "Seared Salmon Fettuccine",
    description: "Atlantic salmon, lemon dill cream, crispy capers",
    category: "Mains",
    price: 12000,
    image_url: img("photo-1563379926898-05f4575a45d8"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 18,
    is_available: true,
    current_stock: 12,
    low_stock_threshold: 4,
  },
  {
    id: 4,
    title: "Crispy Avocado Tacos (3x)",
    description: "Tempura avocado, chipotle crema, corn tortilla",
    category: "Starters",
    price: 7000,
    image_url: img("photo-1565299585323-38d6b0865b47"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 10,
    is_available: true,
    current_stock: 25,
    low_stock_threshold: 8,
  },
  {
    id: 5,
    title: "Matcha Lava Cake",
    description: "Uji matcha center, black sesame ice cream",
    category: "Desserts",
    price: 5500,
    image_url: img("photo-1578985545062-69928b1d9587"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 8,
    low_stock_threshold: 3,
  },
  {
    id: 6,
    title: "Chef Special: Tomahawk Ribeye",
    description: "Dry-aged 45 days, red wine jus, truffle fries",
    category: "Chef Specials",
    price: 45000,
    image_url: img("photo-1600891964092-4316c288032e"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 25,
    is_available: true,
    current_stock: 4,
    low_stock_threshold: 3,
  },
  {
    id: 7,
    title: "Iced Lychee Dragonfruit Cooler",
    description: "Lychee, dragonfruit, sparkling soda, mint",
    category: "Coffee & Drinks",
    price: 3000,
    image_url: img("photo-1497534446932-c925b458314e"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 3,
    is_available: true,
    current_stock: 40,
    low_stock_threshold: 10,
  },
  {
    id: 8,
    title: "Burrata & Heirloom Tomato Salad",
    description: "Puglia burrata, balsamic, pine nut pesto",
    category: "Starters",
    price: 8000,
    image_url: img("photo-1540420773420-3366772f4999"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 15,
    low_stock_threshold: 5,
  },
  {
    id: 9,
    title: "Mohinga",
    description: "Myanmar’s iconic catfish rice-noodle soup, crispy fritters, boiled egg, lime",
    category: "Myanmar",
    price: 4500,
    image_url: menuImg("mohinga"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 30,
    low_stock_threshold: 8,
  },
  {
    id: 10,
    title: "Lahpet Thoke",
    description: "Fermented tea leaf salad with crunchy beans, tomato, garlic oil, dried shrimp",
    category: "Myanmar",
    price: 3500,
    image_url: menuImg("lahpet-thoke"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 11,
    title: "Ohn No Khauk Swe",
    description: "Coconut chicken curry noodles, chickpea broth, shallot crisps, lime",
    category: "Myanmar",
    price: 5000,
    image_url: menuImg("ohn-no-khauk-swe"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 14,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 12,
    title: "Shan Khauk Swe (Shan Noodles)",
    description: "Shan State classic — rice noodles, tomato-pork sauce, pickled greens, crushed peanut",
    category: "Myanmar",
    price: 4000,
    image_url: menuImg("shan-noodles"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 10,
    is_available: true,
    current_stock: 25,
    low_stock_threshold: 6,
  },
  {
    id: 13,
    title: "Wet Thar Hin (Pork Curry)",
    description: "Myanmar pork curry with potato, served with steamed rice and raw vegetables",
    category: "Myanmar",
    price: 6000,
    image_url: menuImg("wet-thar-hin-pork"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 16,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 14,
    title: "Nan Gyi Thoke",
    description: "Thick rice noodle salad, chicken, toasted chickpea flour, chilli oil",
    category: "Myanmar",
    price: 4500,
    image_url: menuImg("nan-gyi-thoke"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 11,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 15,
    title: "Laphet Yay",
    description: "Traditional Myanmar milk tea, strong brew, condensed milk, iced or hot",
    category: "Myanmar",
    price: 1500,
    image_url: menuImg("laphet-yay"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 4,
    is_available: true,
    current_stock: 60,
    low_stock_threshold: 12,
  },
  {
    id: 16,
    title: "Shwe Yin Aye",
    description: "Coconut milk dessert with sago, sticky rice, bread cubes, palm sugar syrup",
    category: "Myanmar",
    price: 3000,
    image_url: menuImg("shwe-yin-aye"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 6,
    is_available: true,
    current_stock: 16,
    low_stock_threshold: 4,
  },
  {
    id: 17,
    title: "Coca-Cola Can",
    description: "Chilled 330ml can, served with ice on request",
    category: "Coffee & Drinks",
    price: 1500,
    image_url: img("photo-1554866585-cd94860890b7"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 1,
    is_available: true,
    current_stock: 80,
    low_stock_threshold: 20,
  },
  {
    id: 18,
    title: "Sprite Can",
    description: "Chilled 330ml lemon-lime soda can",
    category: "Coffee & Drinks",
    price: 1500,
    image_url: img("photo-1625772299848-391b6a87d7b3"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 1,
    is_available: true,
    current_stock: 80,
    low_stock_threshold: 20,
  },
  {
    id: 19,
    title: "Pepsi Can",
    description: "Chilled 330ml cola can",
    category: "Coffee & Drinks",
    price: 1500,
    image_url: img("photo-1629203851122-3726ecdf080e"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 1,
    is_available: true,
    current_stock: 80,
    low_stock_threshold: 20,
  },
  {
    id: 20,
    title: "Handmade Orange Juice",
    description: "Freshly pressed oranges, no sugar added, served over ice",
    category: "Coffee & Drinks",
    price: 3500,
    image_url: img("photo-1621506289937-a8e4df240d0b"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 5,
    is_available: true,
    current_stock: 35,
    low_stock_threshold: 8,
  },
  {
    id: 21,
    title: "Handmade Watermelon Juice",
    description: "Blended ripe watermelon, lightly chilled, mint optional",
    category: "Coffee & Drinks",
    price: 3000,
    image_url: img("photo-1587049352846-4a222e784d38"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 5,
    is_available: true,
    current_stock: 30,
    low_stock_threshold: 8,
  },
  {
    id: 22,
    title: "Handmade Mango Juice",
    description: "Seasonal ripe mango, hand-blended, no artificial syrup",
    category: "Coffee & Drinks",
    price: 3500,
    image_url: img("photo-1546173159-315724a31696"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 5,
    is_available: true,
    current_stock: 28,
    low_stock_threshold: 8,
  },
  {
    id: 23,
    title: "Mixed Fruit Juice",
    description: "House blend of seasonal fruits — orange, pineapple, apple",
    category: "Coffee & Drinks",
    price: 4000,
    image_url: img("photo-1622597467836-f3285f2131b8"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 6,
    is_available: true,
    current_stock: 25,
    low_stock_threshold: 6,
  },
  {
    id: 24,
    title: "Handmade Lime Soda",
    description: "Fresh lime, sparkling soda, a touch of sugar syrup, mint",
    category: "Coffee & Drinks",
    price: 2500,
    image_url: img("photo-1513558161293-cdaf765ed2fd"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 4,
    is_available: true,
    current_stock: 40,
    low_stock_threshold: 10,
  },
  {
    id: 25,
    title: "Iced Americano",
    description: "Double espresso over ice with cold water — bold and clean",
    category: "Coffee & Drinks",
    price: 3000,
    image_url: img("photo-1461023058943-07fcbe16d735"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 3,
    is_available: true,
    current_stock: 45,
    low_stock_threshold: 10,
  },
  {
    id: 26,
    title: "Fresh Young Coconut",
    description: "Chilled young coconut water, served in the shell with straw",
    category: "Coffee & Drinks",
    price: 2500,
    image_url: img("photo-1778090970328-3908def01b6e"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 2,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 27,
    title: "Passion Fruit Juice",
    description: "Tangy passion fruit pulp, lightly sweetened, iced",
    category: "Coffee & Drinks",
    price: 3500,
    image_url: img("photo-1775204341640-8a471f66c752"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 5,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 28,
    title: "Bottled Still Water",
    description: "500ml purified still water, chilled",
    category: "Coffee & Drinks",
    price: 1000,
    image_url: img("photo-1548839140-29a749e1cf4d"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 1,
    is_available: true,
    current_stock: 100,
    low_stock_threshold: 24,
  },
  {
    id: 29,
    title: "Kyay Oh",
    description: "Clear pork-broth rice noodles, meatballs, sliced pork, boiled egg, herbs",
    category: "Myanmar",
    price: 5500,
    image_url: menuImg("kyay-oh"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 14,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 30,
    title: "Kyet Thar Hin (Chicken Curry)",
    description: "Home-style Myanmar chicken curry with potato, steamed rice, side salad",
    category: "Myanmar",
    price: 5500,
    image_url: menuImg("kyet-thar-hin"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 16,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 31,
    title: "Tofu Thoke",
    description: "Yellow tofu salad, cabbage, tomato, chickpea flour, chilli oil, lime",
    category: "Myanmar",
    price: 3500,
    image_url: menuImg("tofu-thoke"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 24,
    low_stock_threshold: 6,
  },
  {
    id: 32,
    title: "Htamin Gyaw (Fried Rice)",
    description: "Myanmar-style fried rice with egg, peas, carrot, and house soy seasoning",
    category: "Myanmar",
    price: 4000,
    image_url: menuImg("htamin-gyaw"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 28,
    low_stock_threshold: 8,
  },
  {
    id: 33,
    title: "Samuza (3 pcs)",
    description: "Crispy triangular pastries stuffed with spiced potato and onion",
    category: "Myanmar",
    price: 2500,
    image_url: menuImg("samuza"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 40,
    low_stock_threshold: 10,
  },
  {
    id: 34,
    title: "Mont Di",
    description: "Rakhine thin rice noodles, fish sauce dressing, chilli, coriander, lime",
    category: "Myanmar",
    price: 4500,
    image_url: menuImg("mont-di"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 11,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 35,
    title: "Crispy Spring Rolls (4x)",
    description: "Vegetable spring rolls, sweet chilli dip",
    category: "Starters",
    price: 4000,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Spring_rolls.jpg/960px-Spring_rolls.jpg",
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 10,
    is_available: true,
    current_stock: 30,
    low_stock_threshold: 8,
  },
  {
    id: 36,
    title: "Buffalo Chicken Wings",
    description: "Crispy wings tossed in spicy buffalo sauce, ranch on the side",
    category: "Starters",
    price: 6500,
    image_url: img("photo-1567620832903-9fc6debc209f"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 14,
    is_available: true,
    current_stock: 26,
    low_stock_threshold: 6,
  },
  {
    id: 37,
    title: "Garlic Butter Prawns",
    description: "Pan-seared prawns in garlic butter, chilli flakes, toasted bread",
    category: "Starters",
    price: 7500,
    image_url: img("photo-1633504581786-316c8002b1b9"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 16,
    low_stock_threshold: 4,
  },
  {
    id: 38,
    title: "Tomato Soup & Bread",
    description: "Roasted tomato soup, cream swirl, warm garlic bread",
    category: "Starters",
    price: 3500,
    image_url: img("photo-1476718406336-bb5a9690ee2a"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 39,
    title: "Chicken Fried Rice",
    description: "Wok-fried rice with chicken, egg, spring onion, light soy",
    category: "Mains",
    price: 4500,
    image_url: img("photo-1603133872878-684f208fb84b"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 30,
    low_stock_threshold: 8,
  },
  {
    id: 40,
    title: "Beef Stir-Fry with Rice",
    description: "Tender beef strips, peppers, oyster sauce, steamed jasmine rice",
    category: "Mains",
    price: 6500,
    image_url: img("photo-1604908176997-125f25cc6f3d"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 15,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 41,
    title: "Pad Thai Prawn",
    description: "Rice noodles, prawns, tamarind sauce, peanut, bean sprouts, lime",
    category: "Mains",
    price: 7000,
    image_url: img("photo-1559314809-0d155014e29e"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 14,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 42,
    title: "Grilled Chicken Plate",
    description: "Herb-marinated chicken breast, seasonal vegetables, garlic rice",
    category: "Mains",
    price: 7500,
    image_url: img("photo-1598103442097-8b74394b95c6"),
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 18,
    is_available: true,
    current_stock: 16,
    low_stock_threshold: 4,
  },
  {
    id: 43,
    title: "Vegetable Green Curry",
    description: "Thai-style green curry with tofu and seasonal vegetables, steamed rice",
    category: "Mains",
    price: 5500,
    image_url: img("photo-1455619452474-d2be8b1e70cd"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 14,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 44,
    title: "Spaghetti Bolognese",
    description: "Slow-cooked beef ragu, Parmesan, fresh basil",
    category: "Mains",
    price: 6500,
    image_url: img("photo-1551892374-ecf8754cf8b0"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 16,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 45,
    title: "Club Sandwich",
    description: "Triple-decker chicken, bacon, egg, tomato, lettuce, fries",
    category: "Mains",
    price: 5500,
    image_url: img("photo-1528735602780-2552fd46c7af"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 46,
    title: "Chocolate Brownie",
    description: "Warm fudge brownie, vanilla ice cream, chocolate sauce",
    category: "Desserts",
    price: 4000,
    image_url: img("photo-1606313564200-e75d5e30476c"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 47,
    title: "Mango Sticky Rice",
    description: "Sweet coconut sticky rice, ripe mango, toasted sesame",
    category: "Desserts",
    price: 4500,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Mango_sticky_rice.jpg/960px-Mango_sticky_rice.jpg",
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 6,
    is_available: true,
    current_stock: 14,
    low_stock_threshold: 4,
  },
  {
    id: 48,
    title: "New York Cheesecake",
    description: "Classic baked cheesecake, berry coulis",
    category: "Desserts",
    price: 5000,
    image_url: img("photo-1533134242443-d4fd215305ad"),
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 5,
    is_available: true,
    current_stock: 12,
    low_stock_threshold: 3,
  },
  {
    id: 49,
    title: "Vanilla Soft Serve",
    description: "Creamy soft-serve cone or cup, chocolate drizzle optional",
    category: "Desserts",
    price: 2500,
    image_url: img("photo-1563805042-7684c019e1cb"),
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 2,
    is_available: true,
    current_stock: 40,
    low_stock_threshold: 10,
  },
  {
    id: 50,
    title: "Crispy Calamari",
    description: "Lightly battered squid rings, aioli, lemon wedge",
    category: "Chef Specials",
    price: 8000,
    image_url: img("photo-1565557623262-b51c2513a641"),
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 14,
    low_stock_threshold: 4,
  },
  {
    id: 51,
    title: "Seafood Platter",
    description: "Grilled prawns, calamari, fish fillet, salad, garlic butter, fries",
    category: "Chef Specials",
    price: 18000,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Platter_of_grilled_seafood%2C_Charco_Azul%2C_La_Palma.jpg/960px-Platter_of_grilled_seafood%2C_Charco_Azul%2C_La_Palma.jpg",
    is_vegetarian: false,
    is_gluten_free: true,
    is_spicy: false,
    preparation_time_minutes: 22,
    is_available: true,
    current_stock: 8,
    low_stock_threshold: 3,
  },
  {
    id: 52,
    title: "Shan Tofu Noodles",
    description: "Shan yellow tofu noodles, light broth, crushed peanut, coriander, chilli oil",
    category: "Myanmar",
    price: 4500,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Shan_Tofu_Noodles_in_Mandalay.jpg/960px-Shan_Tofu_Noodles_in_Mandalay.jpg",
    is_vegetarian: true,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 12,
    is_available: true,
    current_stock: 22,
    low_stock_threshold: 6,
  },
  {
    id: 53,
    title: "Mogok Meeshay",
    description: "Shan State rice-noodle meeshay with meat sauce, bean sprouts, garlic oil, lime",
    category: "Myanmar",
    price: 5000,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mogok_Meeshay.jpg/960px-Mogok_Meeshay.jpg",
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: true,
    preparation_time_minutes: 13,
    is_available: true,
    current_stock: 18,
    low_stock_threshold: 5,
  },
  {
    id: 54,
    title: "Myin Khwa Yuet Thoke",
    description: "Pennywort salad — Shan highland greens, peanut, sesame, lime, chilli",
    category: "Myanmar",
    price: 3000,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Pennywort_Salad.jpg/960px-Pennywort_Salad.jpg",
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 8,
    is_available: true,
    current_stock: 20,
    low_stock_threshold: 5,
  },
  {
    id: 55,
    title: "Wet Thar Hin Htoke",
    description: "Steamed pork parcels in leaf wrap, house dipping sauce",
    category: "Myanmar",
    price: 4500,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Wet_tha_hin_htote.JPG/960px-Wet_tha_hin_htote.JPG",
    is_vegetarian: false,
    is_gluten_free: false,
    is_spicy: false,
    preparation_time_minutes: 15,
    is_available: true,
    current_stock: 16,
    low_stock_threshold: 4,
  },
  {
    id: 56,
    title: "Htamin Thoke (Rice Salad)",
    description: "Myanmar rice salad with tomato, cabbage, peanut, chilli oil, lime",
    category: "Myanmar",
    price: 3500,
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Burmese_rice_salad.jpg/960px-Burmese_rice_salad.jpg",
    is_vegetarian: true,
    is_gluten_free: true,
    is_spicy: true,
    preparation_time_minutes: 9,
    is_available: true,
    current_stock: 24,
    low_stock_threshold: 6,
  },
];

/** Myanmar Kyat — whole numbers, e.g. "MMK 4,500". */
export function money(n: number) {
  return new Intl.NumberFormat("en-MM", {
    style: "currency",
    currency: "MMK",
    maximumFractionDigits: 0,
    minimumFractionDigits: 0,
  }).format(Math.round(n));
}

export function parseTableParam(raw: string | string[] | undefined): number | null {
  const value = Array.isArray(raw) ? raw[0] : raw;
  if (!value) return null;
  const n = Number.parseInt(value, 10);
  return n >= 1 && n <= 99 ? n : null;
}

export function guestOrderUrl(baseUrl: string, tableNumber: number) {
  const base = baseUrl.replace(/\/$/, "");
  return `${base}/?table=${tableNumber}`;
}
